"""
Tests for src/ingest.py.

>>> DO NOT EDIT THIS FILE. <<<

Your job is to implement src/ingest.py so that:

    pytest tests/test_ingest.py -v

runs GREEN. These tests define what "correct" means. Read each test — the
assertion tells you exactly what the function must return.
"""

from pathlib import Path
import pandas as pd
import pytest

from src.ingest import load_prices, clean_prices, load_all_prices

DATA_DIR = Path('data/raw')


# ---------- load_prices ----------

def test_load_prices_returns_dataframe():
    df = load_prices(DATA_DIR / 'aapl.csv')
    assert isinstance(df, pd.DataFrame)


def test_load_prices_columns_and_order():
    df = load_prices(DATA_DIR / 'aapl.csv')
    assert list(df.columns) == ['date', 'ticker', 'close']


def test_load_prices_date_is_datetime():
    df = load_prices(DATA_DIR / 'aapl.csv')
    assert pd.api.types.is_datetime64_any_dtype(df['date'])


def test_load_prices_ticker_is_lowercase_filename_stem():
    df = load_prices(DATA_DIR / 'aapl.csv')
    assert (df['ticker'] == 'aapl').all()


def test_load_prices_close_is_numeric():
    df = load_prices(DATA_DIR / 'aapl.csv')
    assert pd.api.types.is_numeric_dtype(df['close'])


# ---------- clean_prices ----------

def test_clean_prices_drops_nan_close():
    dirty = pd.DataFrame({
        'date': pd.to_datetime(['2025-01-02', '2025-01-03', '2025-01-04']),
        'ticker': ['aapl', 'aapl', 'aapl'],
        'close': [150.0, None, 152.0],
    })
    clean = clean_prices(dirty)
    assert clean['close'].notna().all()
    assert len(clean) == 2


def test_clean_prices_sorts_by_date():
    unsorted = pd.DataFrame({
        'date': pd.to_datetime(['2025-01-04', '2025-01-02', '2025-01-03']),
        'ticker': ['aapl'] * 3,
        'close': [152.0, 150.0, 151.0],
    })
    clean = clean_prices(unsorted)
    assert clean['date'].is_monotonic_increasing


def test_clean_prices_drops_duplicates():
    with_dups = pd.DataFrame({
        'date': pd.to_datetime(['2025-01-02', '2025-01-02', '2025-01-03']),
        'ticker': ['aapl', 'aapl', 'aapl'],
        'close': [150.0, 150.0, 151.0],
    })
    clean = clean_prices(with_dups)
    assert len(clean) == 2


def test_clean_prices_resets_index():
    df = pd.DataFrame({
        'date': pd.to_datetime(['2025-01-02', '2025-01-03']),
        'ticker': ['aapl', 'aapl'],
        'close': [150.0, 151.0],
    }, index=[10, 20])
    clean = clean_prices(df)
    assert list(clean.index) == [0, 1]


# ---------- load_all_prices ----------

def test_load_all_prices_combines_all_tickers():
    df = load_all_prices(DATA_DIR)
    tickers = set(df['ticker'].unique())
    assert tickers == {'aapl', 'msft', 'goog'}


def test_load_all_prices_returns_dataframe():
    df = load_all_prices(DATA_DIR)
    assert isinstance(df, pd.DataFrame)
    assert len(df) > 0


def test_load_all_prices_raises_for_missing_folder():
    with pytest.raises(FileNotFoundError):
        load_all_prices('does/not/exist')


def test_load_all_prices_raises_for_empty_folder(tmp_path):
    # tmp_path is a pytest fixture — a real empty directory
    with pytest.raises(FileNotFoundError):
        load_all_prices(tmp_path)
