"""
Tests for src/metrics.py.

>>> DO NOT EDIT THIS FILE. <<<

Your job is to implement src/metrics.py so that:

    pytest tests/test_metrics.py -v

runs GREEN. Read each test to understand exactly what the function must do.
"""

import numpy as np
import pandas as pd
import pytest

from src.metrics import (
    daily_returns,
    cumulative_returns,
    annualized_volatility,
    sharpe_ratio,
    max_drawdown,
)


# ---------- daily_returns ----------

def test_daily_returns_length_is_n_minus_1():
    prices = pd.Series([100.0, 101.0, 102.01, 100.9899, 102.0])
    r = daily_returns(prices)
    assert len(r) == len(prices) - 1


def test_daily_returns_first_value():
    prices = pd.Series([100.0, 101.0, 102.01, 100.9899, 102.0])
    r = daily_returns(prices)
    # (101 - 100) / 100 = 0.01
    assert r.iloc[0] == pytest.approx(0.01, abs=1e-6)


def test_daily_returns_drops_leading_nan():
    prices = pd.Series([100.0, 105.0, 110.25])
    r = daily_returns(prices)
    assert r.notna().all()


# ---------- cumulative_returns ----------

def test_cumulative_returns_final_matches_compound():
    returns = pd.Series([0.01, 0.01, -0.01, 0.01])
    cum = cumulative_returns(returns)
    expected = (1.01 * 1.01 * 0.99 * 1.01) - 1
    assert cum.iloc[-1] == pytest.approx(expected, abs=1e-6)


def test_cumulative_returns_first_value_matches_first_return():
    returns = pd.Series([0.05, -0.02, 0.03])
    cum = cumulative_returns(returns)
    assert cum.iloc[0] == pytest.approx(0.05, abs=1e-6)


# ---------- annualized_volatility ----------

def test_annualized_volatility_scales_by_sqrt_252():
    returns = pd.Series([0.01, -0.01, 0.02, -0.02, 0.01])
    daily_vol = returns.std()
    result = annualized_volatility(returns)
    assert result == pytest.approx(daily_vol * np.sqrt(252), abs=1e-6)


def test_annualized_volatility_honors_periods_per_year():
    returns = pd.Series([0.01, -0.01, 0.02, -0.02, 0.01])
    daily_vol = returns.std()
    result = annualized_volatility(returns, periods_per_year=52)
    assert result == pytest.approx(daily_vol * np.sqrt(52), abs=1e-6)


# ---------- sharpe_ratio ----------

def test_sharpe_ratio_positive_for_positive_excess_return():
    # Deterministic series: positive daily mean, some noise → positive Sharpe
    np.random.seed(0)
    returns = pd.Series(np.random.normal(0.001, 0.01, 200))
    sr = sharpe_ratio(returns, risk_free_rate=0.02)
    assert sr > 0


def test_sharpe_ratio_negative_for_negative_excess_return():
    np.random.seed(0)
    returns = pd.Series(np.random.normal(-0.001, 0.01, 200))
    sr = sharpe_ratio(returns, risk_free_rate=0.02)
    assert sr < 0


def test_sharpe_ratio_matches_formula():
    np.random.seed(1)
    returns = pd.Series(np.random.normal(0.0005, 0.012, 100))
    rf = 0.03
    expected = (returns.mean() * 252 - rf) / (returns.std() * np.sqrt(252))
    assert sharpe_ratio(returns, risk_free_rate=rf) == pytest.approx(expected, abs=1e-6)


# ---------- max_drawdown ----------

def test_max_drawdown_is_negative_for_declining_series():
    # Peak wealth = 1.20 (at cum = 0.20), trough wealth = 0.90 (at cum = -0.10)
    # Drawdown = (0.90 - 1.20) / 1.20 = -0.25
    cum = pd.Series([0.0, 0.10, 0.20, 0.05, -0.10])
    assert max_drawdown(cum) == pytest.approx(-0.25, abs=1e-6)


def test_max_drawdown_zero_for_monotonic_series():
    cum = pd.Series([0.0, 0.01, 0.02, 0.03, 0.05])
    assert max_drawdown(cum) == pytest.approx(0.0, abs=1e-6)
